supertokens/core-driver-interface

v2.8.0.md

To reflect changes made in 
https://github.com/supertokens/supertokens-core/pull/267 and https://github.com/supertokens/supertokens-plugin-interface/pull/17

Add session handle to /recipe/session GET response

---

api_spec.yaml

Overview
- Updates CDI version
- Adds API spec for creating a signed JWT token
- Adds API spec for getting all JWKs

Add API specs for JWT recipe

---

api_spec.yaml

Removed unnecessary refs for request body and response
https://github.com/supertokens/docs/issues/103
none

remove unnecessary refs

---

api_spec.yaml

- Increased version number
- Added `/user/remove`

Adding delete user endpoint

---

api_spec.yaml

Adding the userId to the reset password consume API response
Related: supertokens/supertokens-core#327

Adding userId to the reset password consume API response

---

.github/workflows/github-actions-changelog.yml
CHANGELOG.md

- https://github.com/supertokens/for-zenhub/issues/101
- adds CHANGELOG.md and associated action

Add changelog

---

CHANGELOG.md
api_spec.yaml

Adding endpoints of the user metadata feature

feat(user-metadata): add user metadata APIs

---

api_spec.yaml

- rid optional for all apis
- userId made required for /recipe/user/metadata

rid optional for all apis

---

CHANGELOG.md
api_spec.yaml

- Adds APIs for User Role recipe
- https://github.com/supertokens/supertokens-core/issues/382

feat: adds user roles

---

CHANGELOG.md
api_spec.yaml

Adds UserId Mapping APIs.
- https://github.com/supertokens/supertokens-core/issues/463

Adds userid mapping

---

CHANGELOG.md
api_spec.yaml

https://github.com/supertokens/supertokens-core/pull/489

2.16 useridmapping changes

---

api_spec.yaml

Regarding multi-tenancy recipe:
- Added 2 APIs for user association with tenant.
- Updated existing APIs to work with existing core changes.

fix: Multitenant apis

---

api_spec.yaml

fix: updated error response for create oauth2 client

fix : Update api_spec.yaml for create oauth2 client api

---

api_spec.yaml

contract changes to create oauth2_client api

docs: added flow diagram and other changes to create oauth2_client api contract

---

api_spec.yaml

changes made on get oauth2_client api contract  and added a flow diagram

docs: get oauth2_client api contract changes

---

api_spec.yaml

Added flow diagram and made spec changes to `post oauth2clientscopes` api contract

docs: changes to oauth_2_client_scopes api

---

api_spec.yaml

Added flow diagram and changes to spec in create scope api

docs: changes to create scope api

---

CHANGELOG.md
api_spec.yaml

added flow diagram and spec changes to put `oauth2` api

docs: changes to put oauth2 scope api

---

CHANGELOG.md
api_spec.yaml

Added flow diagram and spec changes to `get oauth2 scopes` api

docs: changes to get oauth2 scope api

---

CHANGELOG.md
api_spec.yaml

added flow diagram and changes to spec in `delete oauth2 scopes api`
Also, resolved syntax issues in `delete ouath2 client api `

docs: changes to delete oauth2 scopes api

---

CHANGELOG.md
api_spec.yaml

Added flow diagram as well api spec changes tp`create Oauth2 auth code` api.

docs: changes to create auth code api

---

api_spec.yaml

Added flow diagram and spec changes to `delete/revoke auth_token api`.
- https://github.com/supertokens/supertokens-core/issues/582

docs: changes to delete ouath2 token api

---

api_spec.yaml

Added flow diagram as well as spec changes to `verify auth token api`
- https://github.com/supertokens/supertokens-core/issues/582

docs: changes to verify auth token api

---

api_spec.yaml

Made changes to include only client details in response of `get client` api.

docs: response struct changes in get client api

---

api_spec.yaml

Api to get `token info` from refresh token details.

docs: added get refresh token to api spec

---

api_spec.yaml

docs: added new api  to get auth code info

---

CHANGELOG.md
api_spec.yaml

Added flow diagram and  spec changes to `create oauth2 token api`
- https://github.com/supertokens/supertokens-core/issues/582

docs: changes to create oauth2 token api

---

api_spec.yaml

Added new query param `accessTokenHash` to delete token api.
Changes flow diagram as well.

docs: changes to delete token api

---

CHANGELOG.md
api_spec.yaml

API spec updates for account linking

fix: account linking APIs

---

CHANGELOG.md
api_spec.yaml

fix: requests stats API
